version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: translator-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - translator-net
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload  # 👈 auto reload!  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: translator-frontend
    ports:
      - "3000:80"
    networks:
      - translator-net

networks:
  translator-net:
    driver: bridge
